/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2014-08-15 23:20:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


String email = (String) session.getAttribute("email");
String password = (String) session.getAttribute("password");

if (email != null && password != null) {
    response.sendRedirect("main-page.jsp");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Borey</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/index.css\">\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/index.js\"></script>\r\n");
      out.write("    <script src=\"./js/prefixfree.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("        <div class=\"middle\">\r\n");
      out.write("            <div id=\"site\">\r\n");
      out.write("                <div id=\"header\">\r\n");
      out.write("                    <div id=\"logo\">\r\n");
      out.write("                        <h1>\r\n");
      out.write("                            <span id=\"itrium\">itrium</span>.borey</h1>\r\n");
      out.write("                        <span id=\"slogan\">инновации со смыслом</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"authorization\">\r\n");
      out.write("                        <div class=\"title\">Авторизация</div>\r\n");
      out.write("                        <form autocomplete=\"off\">\r\n");
      out.write("                            <input style=\"display:none\">\r\n");
      out.write("                            <input type=\"password\" style=\"display:none\">\r\n");
      out.write("                            <input id=\"authorization_email\" class=\"inp\" type=\"email\" name=\"email\" placeholder=\"Email: \" autocomplete=\"off\">\r\n");
      out.write("                            <input id=\"authorization_password\" class=\"inp\" type=\"password\" name=\"password\" placeholder=\"Password: \" autocomplete=\"off\">\r\n");
      out.write("                            <div id=\"buttons\">\r\n");
      out.write("                                <div id=\"enter\" class=\"btn\">Войти</div>\r\n");
      out.write("                                <div id=\"to_reg\" class=\"btn\">Регистрация</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <!-- <div id=\"forget\">\r\n");
      out.write("                            <a href=\"\">Забыл пароль</a>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"registration\">\r\n");
      out.write("                        <div class=\"title\">Регистрация</div>\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <input style=\"display:none\">\r\n");
      out.write("                            <input type=\"password\" style=\"display:none\">\r\n");
      out.write("                            <input id=\"registration_email\" class=\"inp\" type=\"email\" placeholder=\"Email: \">\r\n");
      out.write("                            <input id=\"registration_password\" class=\"inp\" type=\"password\" placeholder=\"Password: \">\r\n");
      out.write("                            <input id=\"registration_confirm\" class=\"inp\" type=\"password\" placeholder=\"Confirm: \">\r\n");
      out.write("                            <div id=\"buttons\">\r\n");
      out.write("                                <div id=\"back\" class=\"btn\">Назад</div>\r\n");
      out.write("                                <div id=\"reg\" class=\"btn\">Зарегистрироваться</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"content\">\r\n");
      out.write("                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute ex irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ea pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur qui adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate in velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat nisi amet cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est mollit laborum veniam.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"about_contacts\">\r\n");
      out.write("                    <div id=\"about\">\r\n");
      out.write("                        <div class=\"title\">О нас</div>\r\n");
      out.write("                        <div class=\"simple_text\">\r\n");
      out.write("                            <span class=\"important_text\">Itrium</span>- компания, создающая программное обеспечение интегрированных систем безопасности. Программные средства автоматизации бизнес-процессов объекта и видеонаблюдения.\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"contacts\">\r\n");
      out.write("                        <div class=\"title\">Контакты</div>\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"important_text\">Телефон и факс:</td>\r\n");
      out.write("                                <td class=\"simple_text\">+7 (812) 960-06-13</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"important_text\">Email:</td>\r\n");
      out.write("                                <td class=\"simple_text\">interop@itrium.ru</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"copyright\">Designed by <b>Vladislav Romanov</b>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
